shallow_clone: true

os:
  - Visual Studio 2019

environment:
  matrix:
  
  - TOOLSET: vs2019

configuration:
  
  - Release

install:
  - git clone --depth 1 https://github.com/bkaradzic/bx ..\bx
  - git clone --depth 1 https://github.com/bkaradzic/bimg ..\bimg
  - ..\bx\tools\bin\windows\genie --with-tools --with-examples %TOOLSET%

build:
  project: .build/projects/$(TOOLSET)/bgfx.sln
  
  
artifacts:

  # pushing a single file
  - path: test.zip
